# ============================================================
# Assistant API — Main /ask Endpoint
# ============================================================
"""
The primary endpoint where students ask academic questions.
Orchestrates the full pipeline: routing → processing → response.
"""

from __future__ import annotations

import logging
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.middleware import get_current_user, get_optional_user
from app.auth.schemas import TokenPayload
from app.db.schemas import AskRequest, AskResponse, QueryType
from app.decision.engine import process_query, process_query_stream, rewrite_follow_up_query
from app.dependencies import get_db_session
from app.memory.conversation import get_conversation_context, get_session_count
from app.router.query_router import classify_query

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Academic Assistant"])


@router.post(
    "/ask",
    response_model=AskResponse,
    summary="Ask an Academic Question",
    description="""
    Submit an academic question to the intelligent assistant.

    The system will:
    1. Classify the question type (SQL, RAG, or Hybrid)
    2. Retrieve relevant student data and/or regulations
    3. Apply policy rules and generate a reasoned answer
    4. Return the answer with citations and decision details

    **Examples:**
    - "What is my GPA?" → SQL query
    - "What is the withdrawal policy?" → RAG retrieval
    - "Can I register for Internship 2?" → Hybrid decision
    """,
)
async def ask_question(
    request: AskRequest,
    session: AsyncSession = Depends(get_db_session),
    current_user: Optional[TokenPayload] = Depends(get_optional_user),
):
    """
    Main endpoint for academic questions.

    Authentication is optional but recommended — when authenticated,
    the system automatically uses the student's ID from the JWT token.
    """
    # Determine student_id: from request, or from JWT token
    student_id = request.student_id
    user_id = None

    if current_user:
        user_id = current_user.user_id
        if student_id is None:
            student_id = current_user.student_id

    # Generate session_id if not provided (for conversation continuity)
    session_id = request.session_id or str(uuid.uuid4())

    # Step 0.5: Check for conversation memory and rewrite follow-up questions
    search_question = request.question
    if request.session_id:
        try:
            msg_count = await get_session_count(session, session_id)
            if msg_count > 0:
                context = await get_conversation_context(session, session_id)
                if context:
                    search_question = await rewrite_follow_up_query(request.question, context)
        except Exception as e:
            logger.error(f"Error getting conversation history/rewriting query: {e}", exc_info=True)

    logger.info(
        f"[ASK] question='{request.question[:60]}...', "
        f"rewritten='{search_question[:60]}...', "
        f"student_id={student_id}, user_id={user_id}, session={session_id}"
    )

    # Step 1: Classify the query using search_question
    classification = await classify_query(search_question)
    query_type = classification["query_type"]

    logger.info(
        f"[ROUTER] type={query_type.value}, "
        f"confidence={classification.get('confidence', 'N/A')}, "
        f"method={classification.get('method', 'N/A')}"
    )

    # Step 1.5: Reject off-topic questions immediately
    if query_type == QueryType.OFF_TOPIC:
        logger.info(f"[OFF_TOPIC] Rejected: '{request.question[:60]}'")
        from app.db.schemas import AskResponse  # import locally if needed, but it is imported globally now (or wait, we removed it from global imports so let's import it locally/globally)
        return AskResponse(
            answer=(
                "عذراً، أنا مخصص فقط للإجابة على الأسئلة الأكاديمية والجامعية. "
                "يمكنك سؤالي عن المعدل التراكمي، التسجيل، المواد، التخرج، اللوائح الجامعية، وغيرها من الشؤون الأكاديمية. 🎓"
            ),
            query_type=query_type,
            session_id=session_id,
        )

    # Step 2: Process through Decision Engine
    response = await process_query(
        question=request.question,
        query_type=query_type,
        student_id=student_id,
        session=session,
        session_id=session_id,
        user_id=user_id,
        search_question=search_question,
    )

    return response


@router.post(
    "/ask/stream",
    summary="Ask an Academic Question (Streaming)",
    description="""
    Submit an academic question with streaming response via SSE.
    Tokens are sent as they are generated by the LLM.
    """,
)
async def ask_question_stream(
    request: AskRequest,
    session: AsyncSession = Depends(get_db_session),
    current_user: Optional[TokenPayload] = Depends(get_optional_user),
):
    """
    Streaming version of the /ask endpoint.
    Returns Server-Sent Events (SSE) with tokens as they're generated.
    """
    from fastapi.responses import StreamingResponse

    student_id = request.student_id
    user_id = None

    if current_user:
        user_id = current_user.user_id
        if student_id is None:
            student_id = current_user.student_id

    session_id = request.session_id or str(uuid.uuid4())

    # Check for conversation memory and rewrite follow-up questions
    search_question = request.question
    if request.session_id:
        try:
            msg_count = await get_session_count(session, session_id)
            if msg_count > 0:
                context = await get_conversation_context(session, session_id)
                if context:
                    search_question = await rewrite_follow_up_query(request.question, context)
        except Exception as e:
            logger.error(f"Error getting conversation history/rewriting query in stream: {e}", exc_info=True)

    # Classify the query using search_question
    classification = await classify_query(search_question)
    query_type = classification["query_type"]

    logger.info(
        f"[STREAM] type={query_type.value}, "
        f"confidence={classification.get('confidence', 'N/A')}, "
        f"rewritten='{search_question[:60]}...'"
    )

    # Reject off-topic questions immediately (no streaming needed)
    if query_type == QueryType.OFF_TOPIC:
        logger.info(f"[OFF_TOPIC] Rejected (stream): '{request.question[:60]}'")
        import json as _json

        off_topic_answer = (
            "عذراً، أنا مخصص فقط للإجابة على الأسئلة الأكاديمية والجامعية. "
            "يمكنك سؤالي عن المعدل التراكمي، التسجيل، المواد، التخرج، اللوائح الجامعية، وغيرها من الشؤون الأكاديمية. 🎓"
        )

        async def _off_topic_stream():
            # Send the answer as a single metadata event
            yield f"event: metadata\ndata: {_json.dumps({'answer': off_topic_answer, 'query_type': 'OFF_TOPIC', 'session_id': session_id}, ensure_ascii=False)}\n\n"

        return StreamingResponse(
            _off_topic_stream(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    # Return streaming response
    generator = process_query_stream(
        question=request.question,
        query_type=query_type,
        student_id=student_id,
        session=session,
        session_id=session_id,
        user_id=user_id,
        search_question=search_question,
    )

    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get(
    "/history/{session_id}",
    summary="Get Conversation History",
    description="Retrieve the conversation history for a specific session.",
)
async def get_history(
    session_id: str,
    session: AsyncSession = Depends(get_db_session),
    current_user: TokenPayload = Depends(get_current_user),
):
    """Get conversation history for a session."""
    from app.memory.conversation import get_conversation_history

    history = await get_conversation_history(session, session_id)
    return {"session_id": session_id, "messages": history, "count": len(history)}
