# ============================================================
# Assistant API — Main /ask Endpoint
# ============================================================
"""
The primary endpoint where students ask academic questions.
Orchestrates the full pipeline: routing → processing → response.
"""

from __future__ import annotations

import logging
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.middleware import get_current_user, get_optional_user
from app.auth.schemas import TokenPayload
from app.db.schemas import AskRequest, AskResponse
from app.decision.engine import process_query, process_query_stream
from app.dependencies import get_db_session
from app.router.query_router import classify_query

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Academic Assistant"])


@router.post(
    "/ask",
    response_model=AskResponse,
    summary="Ask an Academic Question",
    description="""
    Submit an academic question to the intelligent assistant.

    The system will:
    1. Classify the question type (SQL, RAG, or Hybrid)
    2. Retrieve relevant student data and/or regulations
    3. Apply policy rules and generate a reasoned answer
    4. Return the answer with citations and decision details

    **Examples:**
    - "What is my GPA?" → SQL query
    - "What is the withdrawal policy?" → RAG retrieval
    - "Can I register for Internship 2?" → Hybrid decision
    """,
)
async def ask_question(
    request: AskRequest,
    session: AsyncSession = Depends(get_db_session),
    current_user: Optional[TokenPayload] = Depends(get_optional_user),
):
    """
    Main endpoint for academic questions.

    Authentication is optional but recommended — when authenticated,
    the system automatically uses the student's ID from the JWT token.
    """
    # Determine student_id: from request, or from JWT token
    student_id = request.student_id
    user_id = None

    if current_user:
        user_id = current_user.user_id
        if student_id is None:
            student_id = current_user.student_id

    # Generate session_id if not provided (for conversation continuity)
    session_id = request.session_id or str(uuid.uuid4())

    logger.info(
        f"[ASK] question='{request.question[:60]}...', "
        f"student_id={student_id}, user_id={user_id}, session={session_id}"
    )

    # Step 1: Classify the query
    classification = await classify_query(request.question)
    query_type = classification["query_type"]

    logger.info(
        f"[ROUTER] type={query_type.value}, "
        f"confidence={classification.get('confidence', 'N/A')}, "
        f"method={classification.get('method', 'N/A')}"
    )

    # Step 2: Process through Decision Engine
    response = await process_query(
        question=request.question,
        query_type=query_type,
        student_id=student_id,
        session=session,
        session_id=session_id,
        user_id=user_id,
    )

    return response


@router.post(
    "/ask/stream",
    summary="Ask an Academic Question (Streaming)",
    description="""
    Submit an academic question with streaming response via SSE.
    Tokens are sent as they are generated by the LLM.
    """,
)
async def ask_question_stream(
    request: AskRequest,
    session: AsyncSession = Depends(get_db_session),
    current_user: Optional[TokenPayload] = Depends(get_optional_user),
):
    """
    Streaming version of the /ask endpoint.
    Returns Server-Sent Events (SSE) with tokens as they're generated.
    """
    from fastapi.responses import StreamingResponse

    student_id = request.student_id
    user_id = None

    if current_user:
        user_id = current_user.user_id
        if student_id is None:
            student_id = current_user.student_id

    session_id = request.session_id or str(uuid.uuid4())

    # Classify the query
    classification = await classify_query(request.question)
    query_type = classification["query_type"]

    logger.info(
        f"[STREAM] type={query_type.value}, "
        f"confidence={classification.get('confidence', 'N/A')}"
    )

    # Return streaming response
    generator = process_query_stream(
        question=request.question,
        query_type=query_type,
        student_id=student_id,
        session=session,
        session_id=session_id,
        user_id=user_id,
    )

    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get(
    "/history/{session_id}",
    summary="Get Conversation History",
    description="Retrieve the conversation history for a specific session.",
)
async def get_history(
    session_id: str,
    session: AsyncSession = Depends(get_db_session),
    current_user: TokenPayload = Depends(get_current_user),
):
    """Get conversation history for a session."""
    from app.memory.conversation import get_conversation_history

    history = await get_conversation_history(session, session_id)
    return {"session_id": session_id, "messages": history, "count": len(history)}
